name: Dispatch PR Open Event

on:
  pull_request:
    types: [opened]

jobs:
  dispatch-to-private:
    # Only run this job if the PR is opened in the base repo, not in a fork
    if: github.repository == 'Polkadot-Fast-Grants/apply'
    runs-on: ubuntu-latest

    steps:
      - name: Send repository_dispatch to Internal-Reviews
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DISPATCH_TOKEN }}" \
            https://api.github.com/repos/Polkadot-Fast-Grants/Internal-Reviews/dispatches \
            -d '{
              "event_type": "pr_opened",
              "client_payload": {
                "pr_title": "${{ github.event.pull_request.title }}",
                "pr_url": "${{ github.event.pull_request.html_url }}",
                "pr_user": "${{ github.actor }}"
              }
            }'
